// Auto-generated barvy-a-laky navigation data

export const barvyLakyCategoryMap: Record<string, { label: string; subcategories: { slug: string; label: string }[] }> = {
  'barvy-na-zed': {
    label: 'Barvy na zeď',
    subcategories: [
      { slug: 'omyvatelne-barvy-na-zed', label: 'Omyvatelné barvy na zeď' },
      { slug: 'akrylove-barvy-na-zed', label: 'Akrylové barvy na zeď' },
      { slug: 'tonovaci-barvy-na-zed', label: 'Tónovací barvy na zeď' },
    ],
  },
  'barvy-a-laky-na-interiery': {
    label: 'Barvy a laky na interiéry',
    subcategories: [
      { slug: 'barvy-do-loznice', label: 'Barvy do ložnice' },
      { slug: 'barvy-do-obyvaku', label: 'Barvy do obýváku' },
      { slug: 'barvy-a-laky-na-podlahy', label: 'Barvy a laky na podlahy' },
      { slug: 'barvy-a-laky-na-nabytek', label: 'Barvy a laky na nábytek' },
      { slug: 'barvy-a-laky-na-obklady', label: 'Barvy a laky na obklady' },
      { slug: 'barvy-a-laky-na-schodiste', label: 'Barvy a laky na schodiště' },
      { slug: 'oleje-na-kuchynske-desky', label: 'Oleje na kuchyňské desky' },
      { slug: 'barvy-a-laky-do-sauny', label: 'Barvy a laky do sauny' },
      { slug: 'impregnace-interier', label: 'Impregnace' },
      { slug: 'barvy-na-thermowood-interier', label: 'Barvy na ThermoWood do interiéru' },
      { slug: 'barvy-proti-starnuti-dreva-interier', label: 'Barvy proti stárnutí dřeva do interiéru' },
      { slug: 'michane-barvy-na-drevo-interier', label: 'Míchané barvy na dřevo do interiéru' },
    ],
  },
  'barvy-a-laky-na-exteriery': {
    label: 'Barvy a laky na exteriéry',
    subcategories: [
      { slug: 'barvy-a-laky-na-ploty', label: 'Barvy a laky na ploty' },
      { slug: 'barvy-a-laky-na-fasady', label: 'Barvy a laky na fasády' },
      { slug: 'barvy-a-laky-na-okna-a-dvere', label: 'Barvy a laky na okna a dveře' },
      { slug: 'barvy-a-laky-na-strechy', label: 'Barvy a laky na střechy' },
      { slug: 'barvy-a-laky-na-terasy', label: 'Barvy a laky na terasy' },
      { slug: 'barvy-a-laky-na-pergoly', label: 'Barvy a laky na pergoly' },
      { slug: 'barvy-a-laky-na-zahradni-nabytek', label: 'Barvy a laky na zahradní nábytek' },
      { slug: 'impregnace-dreva', label: 'Impregnace dřeva' },
      { slug: 'olej-pro-wpc-exterier', label: 'Olej pro WPC' },
      { slug: 'olej-na-vyvyseny-zahon', label: 'Olej na vyvýšený záhon' },
      { slug: 'barvy-na-thermowood-exterier', label: 'Barvy na ThermoWood do exteriéru' },
      { slug: 'michane-barvy-na-drevo-exterier', label: 'Míchané barvy na dřevo do exteriéru' },
    ],
  },
  'ostatni-barvy': {
    label: 'Ostatní',
    subcategories: [
      { slug: 'barvy-na-plasty', label: 'Barvy na plasty' },
      { slug: 'malirske-barvy', label: 'Malířské barvy' },
      { slug: 'barvy-ve-spreji', label: 'Barvy ve spreji' },
      { slug: 'barvy-na-thermowood', label: 'Barvy na ThermoWood' },
      { slug: 'olej-na-wpc', label: 'Olej na WPC' },
      { slug: 'barvy-proti-starnuti-dreva', label: 'Barvy proti stárnutí dřeva' },
      { slug: 'barvy-na-beton', label: 'Barvy na beton, kámen a další materiály' },
      { slug: 'vosky-na-drevo', label: 'Vosky na dřevo' },
    ],
  },
  'podle-znacek': {
    label: 'Podle značek',
    subcategories: [
      { slug: '4cr', label: 'Barvy 4CR' },
      { slug: 'a-s-creation', label: 'Barvy A.S. Création' },
      { slug: 'abamal', label: 'Barvy Abamal' },
      { slug: 'aci', label: 'Barvy ACI' },
      { slug: 'adler-cesko', label: 'Barvy Adler Česko' },
      { slug: 'aerosol-service', label: 'Barvy Aerosol - service' },
      { slug: 'ag-termopasty', label: 'Barvy AG TERMOPASTY' },
      { slug: 'agama', label: 'Barvy Agama' },
      { slug: 'aktidrevin', label: 'Barvy Aktidřevin' },
      { slug: 'akzo', label: 'Barvy Akzo' },
      { slug: 'akzo-nobel', label: 'Barvy Akzo Nobel' },
      { slug: 'alfachem', label: 'Barvy Alfachem' },
      { slug: 'alkapren', label: 'Barvy Alkapren' },
      { slug: 'alkyton', label: 'Barvy Alkyton' },
      { slug: 'amarit', label: 'Barvy Amarit' },
      { slug: 'apipol-wax', label: 'Barvy Apipol-Wax' },
      { slug: 'articolor', label: 'Barvy Articolor' },
      { slug: 'atlas', label: 'Barvy Atlas' },
      { slug: 'aug-hedinger', label: 'Barvy Aug Hedinger' },
      { slug: 'auson', label: 'Barvy Auson' },
      { slug: 'austis', label: 'Barvy Austis' },
      { slug: 'auto-max', label: 'Barvy Auto-max' },
      { slug: 'av-equen', label: 'Barvy AV EQUEN' },
      { slug: 'bakrylex', label: 'Barvy Bakrylex' },
      { slug: 'bal-hostivar', label: 'Barvy Bal Hostivař' },
      { slug: 'bal-teluria', label: 'Barvy Bal Teluria' },
      { slug: 'balakryl', label: 'Barvy Balakryl' },
      { slug: 'baltech', label: 'Barvy Baltech' },
      { slug: 'barlet', label: 'Barvy Barlet' },
      { slug: 'barvy-a-laky-hostivar', label: 'Barvy Barvy a Laky Hostivař' },
      { slug: 'barvy-a-laky-teluria', label: 'Barvy Barvy a laky Teluria' },
      { slug: 'barvy-herman', label: 'Barvy Barvy Herman' },
      { slug: 'barvy-plus', label: 'Barvy Barvy Plus' },
      { slug: 'baumit', label: 'Barvy Baumit' },
      { slug: 'bbb-barvy', label: 'Barvy BBB barvy' },
      { slug: 'becher-profi', label: 'Barvy Becher Profi' },
      { slug: 'belinka', label: 'Barvy Belinka' },
      { slug: 'bigstone', label: 'Barvy Bigstone' },
      { slug: 'bione-cosmetics', label: 'Barvy BIONE cosmetics' },
      { slug: 'bisil', label: 'Barvy Bisil' },
      { slug: 'bkp-group', label: 'Barvy BKP GROUP' },
      { slug: 'body-color', label: 'Barvy Body Color' },
      { slug: 'bochemit', label: 'Barvy Bochemit' },
      { slug: 'bolix', label: 'Barvy Bolix' },
      { slug: 'boll', label: 'Barvy BOLL' },
      { slug: 'bona', label: 'Barvy Bona' },
      { slug: 'bondex', label: 'Barvy Bondex' },
      { slug: 'bondex-white-spirit', label: 'Barvy BONDEX WHITE SPIRIT' },
      { slug: 'boretech', label: 'Barvy BoreTech' },
      { slug: 'bori', label: 'Barvy Bori' },
      { slug: 'borma-wachs', label: 'Barvy Borma Wachs' },
      { slug: 'brunox', label: 'Barvy Brunox' },
      { slug: 'bsa', label: 'Barvy BSA' },
      { slug: 'building-plast', label: 'Barvy Building Plast' },
      { slug: 'buldok-new', label: 'Barvy BULDOK new' },
      { slug: 'caparol', label: 'Barvy Caparol' },
      { slug: 'carfit', label: 'Barvy Carfit' },
      { slug: 'carline', label: 'Barvy CARLINE' },
      { slug: 'carlson', label: 'Barvy Carlson' },
      { slug: 'cb-chemie-servisni', label: 'Barvy CB Chemie Servisní' },
      { slug: 'cemix', label: 'Barvy Cemix' },
      { slug: 'certak', label: 'Barvy Čerťák' },
      { slug: 'cesky-stavitel', label: 'Barvy ČESKÝ STAVITEL' },
      { slug: 'ciranova', label: 'Barvy Ciranova' },
      { slug: 'citon', label: 'Barvy Citon' },
      { slug: 'cleamen', label: 'Barvy Cleamen' },
      { slug: 'clou', label: 'Barvy Clou' },
      { slug: 'color-company', label: 'Barvy Color Company' },
      { slug: 'colorcity', label: 'Barvy ColorCity' },
      { slug: 'colorex', label: 'Barvy Colorex' },
      { slug: 'colorlak', label: 'Barvy Colorlak' },
      { slug: 'complex-josef-schellhorn', label: 'Barvy Complex - Josef Schellhorn' },
      { slug: 'coyote', label: 'Barvy COYOTE' },
      { slug: 'cyklon', label: 'Barvy CYKLON' },
      { slug: 'dakota-living', label: 'Barvy Dakota Living' },
      { slug: 'dawex-chemical', label: 'Barvy Dawex Chemical' },
      { slug: 'debeer', label: 'Barvy DEBEER' },
      { slug: 'deerfos', label: 'Barvy Deerfos' },
      { slug: 'dekfinish', label: 'Barvy Dekfinish' },
      { slug: 'dekoral', label: 'Barvy Dekoral' },
      { slug: 'den-braven', label: 'Barvy Den Braven' },
      { slug: 'denas', label: 'Barvy Denas' },
      { slug: 'denas-color', label: 'Barvy Denas Color' },
      { slug: 'detecha', label: 'Barvy Detecha' },
      { slug: 'dexoll', label: 'Barvy Dexoll' },
      { slug: 'df-partner', label: 'Barvy DF Partner' },
      { slug: 'dictum', label: 'Barvy Dictum' },
      { slug: 'dispechem', label: 'Barvy Dispechem' },
      { slug: 'distrimo', label: 'Barvy DISTRIMO' },
      { slug: 'druchema', label: 'Barvy Druchema' },
      { slug: 'druchema-lihove-moridlo', label: 'Barvy Druchema Lihové mořidlo' },
      { slug: 'dufa', label: 'Barvy Düfa' },
      { slug: 'dulux', label: 'Barvy Dulux' },
      { slug: 'dupli-color', label: 'Barvy Dupli Color' },
      { slug: 'dynacoat', label: 'Barvy Dynacoat' },
      { slug: 'eco-solutions-limited', label: 'Barvy Eco-Solutions Limited' },
      { slug: 'ecofol', label: 'Barvy ECOFOL' },
      { slug: 'ecoliquid', label: 'Barvy Ecoliquid' },
      { slug: 'elchemco', label: 'Barvy ELCHEMCo' },
      { slug: 'envichem', label: 'Barvy EnviChem' },
      { slug: 'ep-vernici', label: 'Barvy Ep Vernici' },
      { slug: 'epolex', label: 'Barvy Epolex' },
      { slug: 'estetik', label: 'Barvy Estetik' },
      { slug: 'eternal', label: 'Barvy Eternal' },
      { slug: 'euronaradi', label: 'Barvy Euronářadí' },
      { slug: 'expert-line', label: 'Barvy EXPERT LINE' },
      { slug: 'faren', label: 'Barvy Faren' },
      { slug: 'farmicol-spa', label: 'Barvy Farmicol SpA' },
      { slug: 'farrow-ball', label: 'Barvy Farrow & Ball' },
      { slug: 'ferdus', label: 'Barvy Ferdus' },
      { slug: 'finalit', label: 'Barvy Finalit' },
      { slug: 'finess', label: 'Barvy Finess' },
      { slug: 'finkolora', label: 'Barvy Finkolora' },
      { slug: 'flagon', label: 'Barvy Flagon' },
      { slug: 'flugger', label: 'Barvy Flügger' },
      { slug: 'fn-nano', label: 'Barvy FN NANO' },
      { slug: 'forch', label: 'Barvy FORCH' },
      { slug: 'fortekryl', label: 'Barvy Fortekryl' },
      { slug: 'fox', label: 'Barvy Fox' },
      { slug: 'fronton', label: 'Barvy Fronton' },
      { slug: 'gotherm', label: 'Barvy GoTherm' },
      { slug: 'granit', label: 'Barvy Granit' },
      { slug: 'gutta', label: 'Barvy Gutta' },
      { slug: 'hadex', label: 'Barvy Hadex' },
      { slug: 'hahn-color', label: 'Barvy Hahn Color' },
      { slug: 'hammerite', label: 'Barvy Hammerite' },
      { slug: 'havlicek-truhlarstvi', label: 'Barvy Havlíček truhlářství' },
      { slug: 'hb-lak', label: 'Barvy HB-Lak' },
      { slug: 'helios', label: 'Barvy Helios' },
      { slug: 'henkel', label: 'Barvy Henkel' },
      { slug: 'herbol', label: 'Barvy Herbol' },
      { slug: 'het', label: 'Barvy Het' },
      { slug: 'hf-market', label: 'Barvy HF Market' },
      { slug: 'hf-servis', label: 'Barvy HF servis' },
      { slug: 'hg', label: 'Barvy HG' },
      { slug: 'hlubna', label: 'Barvy HLUBNA' },
      { slug: 'hokr', label: 'Barvy Hokr' },
      { slug: 'hornbach', label: 'Barvy Hornbach' },
      { slug: 'hostagrund', label: 'Barvy Hostagrund' },
      { slug: 'howard-products', label: 'Barvy Howard Products' },
      { slug: 'hyperticus-bio', label: 'Barvy Hyperticus Bio' },
      { slug: 'chamaeleon', label: 'Barvy CHAMAELEON' },
      { slug: 'chamaleon', label: 'Barvy Chamaleon' },
      { slug: 'chemolak', label: 'Barvy Chemolak' },
      { slug: 'chemoxyl', label: 'Barvy Chemoxyl' },
      { slug: 'chromos', label: 'Barvy Chromos' },
      { slug: 'chytra-zed', label: 'Barvy Chytrá zeď' },
      { slug: 'icla', label: 'Barvy Icla' },
      { slug: 'impranal', label: 'Barvy Impranal' },
      { slug: 'industrit', label: 'Barvy Industrit' },
      { slug: 'industrol', label: 'Barvy Industrol' },
      { slug: 'inhicor', label: 'Barvy Inhicor' },
      { slug: 'intercut', label: 'Barvy Intercut' },
      { slug: 'izomat-stavebniny', label: 'Barvy IZOMAT stavebniny' },
      { slug: 'jansen', label: 'Barvy Jansen' },
      { slug: 'jeger', label: 'Barvy Jeger' },
      { slug: 'johnstone-s', label: 'Barvy Johnstone´s' },
      { slug: 'johnstones', label: 'Barvy JOHNSTONES' },
      { slug: 'jub', label: 'Barvy Jub' },
      { slug: 'jupol', label: 'Barvy Jupol' },
      { slug: 'k-n-filters', label: 'Barvy K&N Filters' },
      { slug: 'kabe', label: 'Barvy Kabe' },
      { slug: 'kana', label: 'Barvy Kana' },
      { slug: 'kansai-helios', label: 'Barvy Kansai Helios' },
      { slug: 'karcher', label: 'Barvy Karcher' },
      { slug: 'kavan', label: 'Barvy Kavan' },
      { slug: 'khb-keramika', label: 'Barvy KHB Keramika' },
      { slug: 'kittfort', label: 'Barvy Kittfort' },
      { slug: 'klumpp-coatings', label: 'Barvy Klumpp Coatings' },
      { slug: 'km-plus', label: 'Barvy KM PLUS' },
      { slug: 'knauf-insulation', label: 'Barvy Knauf insulation' },
      { slug: 'koh-i-noor', label: 'Barvy Koh-i-noor' },
      { slug: 'koopmans', label: 'Barvy Koopmans' },
      { slug: 'kreul', label: 'Barvy Kreul' },
      { slug: 'kwasny', label: 'Barvy Kwasny' },
      { slug: 'labar', label: 'Barvy Labar' },
      { slug: 'lachner', label: 'Barvy Lachner' },
      { slug: 'lazurol', label: 'Barvy Lazurol' },
      { slug: 'lefranc-amp-bourgeois', label: 'Barvy Lefranc amp Bourgeois' },
      { slug: 'lefranc-amp-bourgeois-2', label: 'Barvy Lefranc amp Bourgeois 2' },
      { slug: 'leinos', label: 'Barvy Leinos' },
      { slug: 'lesonal', label: 'Barvy Lesonal' },
      { slug: 'lignofix', label: 'Barvy Lignofix' },
      { slug: 'liqui-moly', label: 'Barvy LIQUI MOLY' },
      { slug: 'lithofin', label: 'Barvy LITHOFIN' },
      { slug: 'loba', label: 'Barvy Loba' },
      { slug: 'lucebni-zavody', label: 'Barvy Lučební závody' },
      { slug: 'lucebni-zavody-kolin', label: 'Barvy Lučební závody Kolín' },
      { slug: 'luxdecor', label: 'Barvy LuxDecor' },
      { slug: 'luxol', label: 'Barvy Luxol' },
      { slug: 'm-kavis', label: 'Barvy M-Kavis' },
      { slug: 'malir', label: 'Barvy Malíř' },
      { slug: 'mapei', label: 'Barvy Mapei' },
      { slug: 'marty-s', label: 'Barvy Marty’s' },
      { slug: 'mastersil', label: 'Barvy Mastersil' },
      { slug: 'mat-group', label: 'Barvy MAT GROUP' },
      { slug: 'meffert', label: 'Barvy Meffert' },
      { slug: 'metrum', label: 'Barvy METRUM' },
      { slug: 'mipa', label: 'Barvy Mipa' },
      { slug: 'modulan', label: 'Barvy Modulan' },
      { slug: 'montana-cans', label: 'Barvy Montana Cans' },
      { slug: 'morys', label: 'Barvy Morys' },
      { slug: 'motip', label: 'Barvy Motip' },
      { slug: 'murexin', label: 'Barvy Murexin' },
      { slug: 'nanolab', label: 'Barvy Nanolab' },
      { slug: 'nanoprotech', label: 'Barvy Nanoprotech' },
      { slug: 'neotex', label: 'Barvy Neotex' },
      { slug: 'novochema', label: 'Barvy Novochema' },
      { slug: 'novol', label: 'Barvy Novol' },
      { slug: 'obi', label: 'Barvy Obi' },
      { slug: 'odie-s', label: 'Barvy Odie’s' },
      { slug: 'okko', label: 'Barvy Okko' },
      { slug: 'oli-natura', label: 'Barvy Oli-Natura' },
      { slug: 'orlen', label: 'Barvy ORLEN' },
      { slug: 'osmo', label: 'Barvy Osmo' },
      { slug: 'owatrol', label: 'Barvy Owatrol' },
      { slug: 'p-s-r', label: 'Barvy P.S.R.' },
      { slug: 'pallmann', label: 'Barvy Pallmann' },
      { slug: 'pattex', label: 'Barvy Pattex' },
      { slug: 'pebeo', label: 'Barvy Pébéo' },
      { slug: 'pellachrom', label: 'Barvy Pellachrom' },
      { slug: 'penosil', label: 'Barvy PENOSIL' },
      { slug: 'pentart', label: 'Barvy Pentart' },
      { slug: 'perdix', label: 'Barvy Perdix' },
      { slug: 'petec', label: 'Barvy PETEC' },
      { slug: 'pg', label: 'Barvy PG' },
      { slug: 'plastservis', label: 'Barvy Plastservis' },
      { slug: 'pnz', label: 'Barvy PNZ' },
      { slug: 'polykar', label: 'Barvy Polykar' },
      { slug: 'poola', label: 'Barvy Poola' },
      { slug: 'pragoprimer-standard', label: 'Barvy Pragoprimer Standard' },
      { slug: 'praktik', label: 'Barvy Praktik' },
      { slug: 'presto', label: 'Barvy Presto' },
      { slug: 'primacol', label: 'Barvy Primacol' },
      { slug: 'primalex', label: 'Barvy Primalex' },
      { slug: 'prince-color', label: 'Barvy PRINCE COLOR' },
      { slug: 'pro-doma', label: 'Barvy Pro-Doma' },
      { slug: 'pro-tech', label: 'Barvy Pro-Tech' },
      { slug: 'profi-color', label: 'Barvy Profi Color' },
      { slug: 'progold', label: 'Barvy PROGold' },
      { slug: 'prolux', label: 'Barvy Prolux' },
      { slug: 'proxim', label: 'Barvy PROXIM' },
      { slug: 'pufas', label: 'Barvy PUFAS' },
      { slug: 'q-cover', label: 'Barvy Q-Cover' },
      { slug: 'relius', label: 'Barvy Relius' },
      { slug: 'rem-lack-bis', label: 'Barvy REM-LACK BIS' },
      { slug: 'remakol', label: 'Barvy Remakol' },
      { slug: 'remal', label: 'Barvy Remal' },
      { slug: 'rembradtin', label: 'Barvy Rembradtin' },
      { slug: 'remmers', label: 'Barvy Remmers' },
      { slug: 'renesans', label: 'Barvy Renesans' },
      { slug: 'renolast', label: 'Barvy Renolast' },
      { slug: 'revell', label: 'Barvy Revell' },
      { slug: 'riapower', label: 'Barvy RIApower' },
      { slug: 'roko', label: 'Barvy Roko' },
      { slug: 'rokosil-aqua', label: 'Barvy Rokosil Aqua' },
      { slug: 'rokospol', label: 'Barvy Rokospol' },
      { slug: 'rosner', label: 'Barvy Rosner' },
      { slug: 'rubio-monocoat', label: 'Barvy Rubio Monocoat' },
      { slug: 'rust-oleum', label: 'Barvy Rust-Oleum' },
      { slug: 'rustbreaker', label: 'Barvy Rustbreaker' },
      { slug: 'sadolin', label: 'Barvy Sadolin' },
      { slug: 'saicos', label: 'Barvy Saicos' },
      { slug: 'saint-gobain', label: 'Barvy Saint-Gobain' },
      { slug: 'san-marco', label: 'Barvy San Marco' },
      { slug: 'sanax', label: 'Barvy Sanax' },
      { slug: 'scandicare', label: 'Barvy Scandicare' },
      { slug: 'scandiccare', label: 'Barvy Scandiccare' },
      { slug: 'sedlecky-kaolin', label: 'Barvy Sedlecký kaolin' },
      { slug: 'select', label: 'Barvy SELECT' },
      { slug: 'selection', label: 'Barvy Selection' },
      { slug: 'sennelier', label: 'Barvy Sennelier' },
      { slug: 'severochema', label: 'Barvy Severochema' },
      { slug: 'sheron', label: 'Barvy SHERON' },
      { slug: 'schmincke', label: 'Barvy Schmincke' },
      { slug: 'schoner-wohnen', label: 'Barvy Schöner Wohnen' },
      { slug: 'schuller', label: 'Barvy Schuller' },
      { slug: 'schuller-eh-klar', label: 'Barvy Schuller Eh’klar' },
      { slug: 'sigma', label: 'Barvy Sigma' },
      { slug: 'signocryl', label: 'Barvy Signocryl' },
      { slug: 'sika', label: 'Barvy Sika' },
      { slug: 'sikkens', label: 'Barvy Sikkens' },
      { slug: 'slovlak', label: 'Barvy Slovlak' },
      { slug: 'sniezka', label: 'Barvy Sniezka' },
      { slug: 'sokrates', label: 'Barvy Sokrates' },
      { slug: 'soudal', label: 'Barvy Soudal' },
      { slug: 'spektrum', label: 'Barvy Spektrum' },
      { slug: 'spies-hecker', label: 'Barvy Spies Hecker' },
      { slug: 'sps', label: 'Barvy SPS' },
      { slug: 'stahlmann', label: 'Barvy Stahlmann' },
      { slug: 'stachema', label: 'Barvy Stachema' },
      { slug: 'stavebniny-dek', label: 'Barvy Stavebniny DEK' },
      { slug: 'stefan-kupietz-cokg', label: 'Barvy Stefan Kupietz & CoKG' },
      { slug: 'stylecolor', label: 'Barvy StyleColor' },
      { slug: 'supermal', label: 'Barvy Supermal' },
      { slug: 'supralux', label: 'Barvy Supralux' },
      { slug: 'swingcolor', label: 'Barvy Swingcolor' },
      { slug: 'synteko', label: 'Barvy Synteko' },
      { slug: 'tecmaxx', label: 'Barvy TECMAXX' },
      { slug: 'teluria', label: 'Barvy Teluria' },
      { slug: 'tesa', label: 'Barvy TESA' },
      { slug: 'thermilate', label: 'Barvy Thermilate' },
      { slug: 'tikkurila', label: 'Barvy Tikkurila' },
      { slug: 'tkk', label: 'Barvy TKK' },
      { slug: 'topekor', label: 'Barvy Topekor' },
      { slug: 'topstone', label: 'Barvy TOPSTONE' },
      { slug: 'tremco-cpg', label: 'Barvy Tremco CPG' },
      { slug: 'trikolor', label: 'Barvy Trikolor' },
      { slug: 'u-pepanka', label: 'Barvy U Pepánka' },
      { slug: 'uni-hobby', label: 'Barvy Uni Hobby' },
      { slug: 'unibal', label: 'Barvy Unibal' },
      { slug: 'v-i-p-italy', label: 'Barvy V.I.P. Italy' },
      { slug: 'velvana', label: 'Barvy Velvana' },
      { slug: 'venti', label: 'Barvy Venti' },
      { slug: 'vip-italy', label: 'Barvy VIP Italy' },
      { slug: 'vitex', label: 'Barvy Vitex' },
      { slug: 'viton', label: 'Barvy VITON' },
      { slug: 'vivechrom', label: 'Barvy Vivechrom' },
      { slug: 'walrus-oil', label: 'Barvy Walrus Oil' },
      { slug: 'weber', label: 'Barvy Weber' },
      { slug: 'weber-terranova', label: 'Barvy Weber Terranova' },
      { slug: 'wilckens', label: 'Barvy Wilckens' },
      { slug: 'wildschek', label: 'Barvy Wildschek' },
      { slug: 'winsor-newton', label: 'Barvy Winsor & Newton' },
      { slug: 'woca', label: 'Barvy Woca' },
      { slug: 'woldoclean', label: 'Barvy WoldoClean' },
      { slug: 'wolfcraft', label: 'Barvy Wolfcraft' },
      { slug: 'wood-guard', label: 'Barvy Wood Guard' },
      { slug: 'wurth', label: 'Barvy Würth' },
      { slug: 'xyladecor', label: 'Barvy Xyladecor' },
      { slug: 'zinsser', label: 'Barvy ZINSSER' },
    ],
  },
}

// Standalone articles (not categories)
export const barvyLakyStandaloneArticles = [
  { slug: 'barvy-na-drevo', label: 'Barvy na dřevo' },
  { slug: 'barvy-na-kov', label: 'Barvy na kov' },
  { slug: 'barvy-na-fasady-domu', label: 'Barvy na fasády domu' },
]

export function allBarvyLakyArticleSlugs(): string[] {
  const slugs: string[] = []
  for (const cat of Object.values(barvyLakyCategoryMap)) {
    for (const sub of cat.subcategories) {
      slugs.push(sub.slug)
    }
  }
  for (const a of barvyLakyStandaloneArticles) {
    slugs.push(a.slug)
  }
  return slugs
}
